source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'rails-api'
gem 'ruby-oci8'
gem 'activerecord-oracle_enhanced-adapter'
gem 'ruby-plsql'
gem 'hirb-unicode'
gem 'thin'
gem 'pry'
gem 'pry-rails'
gem 'figaro'
gem 'awesome_print'
